### PR TITLE
Fixed var scope issue.

### LINKED ISSUE #3: Second task causes an error "Warning: mergeCopy is not a function Use --force to continue."
I am trying two simple tasks. I have both directory `a` and `b` created with files in them and the two directories are in the root parallel to my Gruntfile.

If I just call `grunt a` or `grunt b`, it works beautifully, when I call the default task I get the error:

_Gruntfile.js_

```
module.exports = function (grunt) {

    grunt.initConfig({

        'merge-copy': {

            a: {
                options: {
                    destination: 'c',
                    directories: ['a', 'b']
                }
            },
            b: {
                options: {
                    destination: 'd',
                    directories: ['c', 'b']
                }
            }
        }



    });
    grunt.loadNpmTasks('grunt-merge-copy');

    grunt.registerTask('default', [

            'merge-copy:a',
            'merge-copy:b'
        ]
    );

};
```

_Terminal Output_

```
grunt -vvv
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "grunt-merge-copy" local Npm module tasks.
Reading /Users/me/deployers/node_modules/grunt-merge-copy/package.json...OK
Parsing /Users/me/deployers/node_modules/grunt-merge-copy/package.json...OK
Loading "merge-copy.js" tasks...OK
+ merge-copy
Loading "Gruntfile.js" tasks...OK
+ default

No tasks specified, running default tasks.
Running tasks: default

Running "default" task

Running "merge-copy:a" (merge-copy) task
Verifying property merge-copy.a exists in config...OK
File: [no files]
Options: destination="c", directories=["a","b"]
Reading a/a.txt...OK
Writing c/a.txt...OK
Reading b/b.txt...OK
Writing c/b.txt...OK

Running "merge-copy:b" (merge-copy) task
Verifying property merge-copy.b exists in config...OK
File: [no files]
Options: destination="d", directories=["c","b"]
Warning: mergeCopy is not a function Use --force to continue.

Aborted due to warnings.

```

### PR DESCRIPTION
**Pull request by gomezd**
Fixes #3

### CODE REVIEW

File: tasks/merge-copy.js [hunk 1]
```diff
@@ -1,22 +1,23 @@
...
-	
+
 	var mergeCopy = require('../lib/merge-copy')(grunt);
 
     grunt.registerMultiTask( 'merge-copy', 'Merge two or more directories', function() {
         var options = this.options(),
-			files = [];
-		
+			files = [],
+			mc;
```
Comment (mquintal) [inline tasks/merge-copy.js:9]: @gomezd  Can you change `mc` for some more descriptive?
